name: google_oauth2_client
version: 0.2.17
authors:
- Gerwin Sturm <scarygami@gmail.com>
- Adam Singer <financeCoding@gmail.com>
- Kevin Moore <kevin@thinkpixellab.com>
description: Library to use for Google OAuth2 authentication / Client-side flow
homepage: https://github.com/dart-gde/dart-google-oauth2-library
environment:
  sdk: '>=0.6.5'
dependencies:
  crypto: '>=0.6.5'
  http: '>=0.6.5'
  oauth2: '>=0.6.5'
  path: '>=0.6.5'
dev_dependencies:
  browser: '>=0.6.5'
  hop: '>=0.24.0'
